spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt.enabled: false
        native:
          search-locations: classpath:/config

server:
  port: 8071
