spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ostock_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

## 로깅 설정 (선택 사항)
logging:
  level:
    org.hibernate.SQL: DEBUG

server:
  port: 8080